app/routes/web.php
    Route::get('warehouse/lims_warehouse_search', 'WarehouseController@limsWarehouseSearch')->name('warehouse.search');

    Route::prefix('warehouse')
        ->name('warehouse.')
        ->group(function () {
            Route::resource('bins', 'WarehouseBinController');
        });

    Route::resource('warehouse', 'WarehouseController');



    Route::post('importtax', 'TaxController@importTax')->name('tax.import');
    Route::post('tax/deletebyselection', 'TaxController@deleteBySelection');
    Route::get('tax/lims_tax_search', 'TaxController@limsTaxSearch')->name('tax.search');
    Route::resource('tax', 'TaxController');

    //Route::get('products/getbarcode', 'ProductController@getBarcode');
    Route::post('products/product-data', '\App\Http\Controllers\V1\ProductController@productData');
    Route::get('products/gencode', 'ProductController@generateCode');
    // Route::get('products/search', 'ProductController@search');
    Route::get('products/search', '\App\Http\Controllers\V1\API\ProductController@search');
    Route::get('products/saleunit/{id}', 'ProductController@saleUnit');
    Route::get('products/getdata/{id}/{variant_id}', 'ProductController@getData');
    Route::get('products/product_warehouse/{id}', '\App\Http\Controllers\V1\ProductController@productWarehouseData');
    Route::post('importproduct', 'ProductController@importProduct')->name('product.import');
    Route::post('exportproduct', 'ProductController@exportProduct')->name('product.export');
    Route::get('products/print_barcode', 'ProductController@printBarcode')->name('product.printBarcode');
    Route::get('products/lims_product_search', 'ProductController@limsProductSearch')->name('product.search');
    Route::post('products/deletebyselection', 'ProductController@deleteBySelection');
    Route::post('products/update', '\App\Http\Controllers\V1\ProductController@updateProduct');
    Route::get('products/variant-data/{id}', 'ProductController@variantData');
    Route::get('products/history', '\App\Http\Controllers\V1\ProductController@history')->name('products.history');
    Route::post('products/sale-history-data', 'ProductController@saleHistoryData');
    Route::post('products/purchase-history-data', 'ProductController@purchaseHistoryData');
    Route::post('products/sale-return-history-data', 'ProductController@saleReturnHistoryData');
    Route::post('products/stock-adjustment-history-data', '\App\Http\Controllers\V1\ProductController@stockAdjustmentHistoryData');
    Route::post('products/stock-transfer-history-data', '\App\Http\Controllers\V1\ProductController@stockTransferHistoryData');

    Route::post('products/purchase-return-history-data', 'ProductController@purchaseReturnHistoryData');
    Route::resource('products', '\App\Http\Controllers\V1\ProductController');
    Route::post('products', '\App\Http\Controllers\V1\ProductController@store_v2')->name('products.store_v2');


    Route::post('importcustomer_group', 'CustomerGroupController@importCustomerGroup')->name('customer_group.import');
    Route::post('customer_group/deletebyselection', 'CustomerGroupController@deleteBySelection');
    Route::get('customer_group/lims_customer_group_search', 'CustomerGroupController@limsCustomerGroupSearch')->name('customer_group.search');
    Route::resource('customer_group', 'CustomerGroupController');

    Route::resource('discount-plans', 'DiscountPlanController');
    Route::resource('discounts', 'DiscountController');
    Route::get('discounts/product-search/{code}', 'DiscountController@productSearch');

    Route::post('importcustomer', 'CustomerController@importCustomer')->name('customer.import');
    Route::get('customer/getDeposit/{id}', 'CustomerController@getDeposit');
    Route::post('customer/add_deposit', 'CustomerController@addDeposit')->name('customer.addDeposit');
    Route::post('customer/update_deposit', 'CustomerController@updateDeposit')->name('customer.updateDeposit');
    Route::post('customer/deleteDeposit', 'CustomerController@deleteDeposit')->name('customer.deleteDeposit');
    Route::post('customer/deletebyselection', 'CustomerController@deleteBySelection');
    Route::get('customer/lims_customer_search', 'CustomerController@limsCustomerSearch')->name('customer.search');
    Route::post('customers/clear-due', 'CustomerController@clearDue')->name('customer.clearDue');
    Route::resource('customer', 'CustomerController');

    Route::post('importbiller', 'BillerController@importBiller')->name('biller.import');
    Route::post('biller/deletebyselection', 'BillerController@deleteBySelection');
    Route::get('biller/lims_biller_search', 'BillerController@limsBillerSearch')->name('biller.search');
    Route::resource('biller', 'BillerController');

    Route::post('sales/sale-data', 'SaleController@saleData');
    Route::post('sales/sendmail', 'SaleController@sendMail')->name('sale.sendmail');
    Route::get('sales/sale_by_csv', 'SaleController@saleByCsv');
    Route::get('sales/product_sale/{id}', 'SaleController@productSaleData');
    Route::post('importsale', 'SaleController@importSale')->name('sale.import');
    Route::get('pos', 'SaleController@posSale')->name('sale.pos');
    Route::get('sales/lims_sale_search', 'SaleController@limsSaleSearch')->name('sale.search');
    Route::get('sales/lims_product_search', 'SaleController@limsProductSearch')->name('product_sale.search');
    Route::get('sales/getcustomergroup/{id}', 'SaleController@getCustomerGroup')->name('sale.getcustomergroup');
    Route::get('sales/getproduct/{id}', 'SaleController@getProduct')->name('sale.getproduct');
    Route::get('sales/getproduct/{category_id}/{brand_id}', 'SaleController@getProductByFilter');
    Route::get('sales/getfeatured', 'SaleController@getFeatured');
    Route::get('sales/get_gift_card', 'SaleController@getGiftCard');
    Route::get('sales/paypalSuccess', 'SaleController@paypalSuccess');
    Route::get('sales/paypalPaymentSuccess/{id}', 'SaleController@paypalPaymentSuccess');
    Route::get('sales/gen_invoice/{id}', 'SaleController@genInvoice')->name('sale.invoice');
    Route::post('sales/add_payment', 'SaleController@addPayment')->name('sale.add-payment');
    Route::get('sales/getpayment/{id}', 'SaleController@getPayment')->name('sale.get-payment');
    Route::post('sales/updatepayment', 'SaleController@updatePayment')->name('sale.update-payment');
    Route::post('sales/deletepayment', 'SaleController@deletePayment')->name('sale.delete-payment');
    Route::get('sales/{id}/create', 'SaleController@createSale');
    Route::post('sales/deletebyselection', 'SaleController@deleteBySelection');
    Route::get('sales/print-last-reciept', 'SaleController@printLastReciept')->name('sales.printLastReciept');
    Route::get('sales/today-sale', 'SaleController@todaySale');
    Route::get('sales/today-profit/{warehouse_id}', 'SaleController@todayProfit');
    Route::get('sales/check-discount', 'SaleController@checkDiscount');


    // This overrides the resource route
    Route::get('sales/{id}/edit', 'V1\SaleController@edit');

    Route::resource('sales', 'SaleController');

    Route::get('sales/create', 'V1\SaleController@create')->name('sales.create');
    Route::get('sales', 'V1\SaleController@index')->name('sales.index');
    Route::post('sales', 'V1\SaleController@store')->name('sales.store');
    Route::get('sale/print/{id}', 'V1\SaleController@print')->name('sale.print');

    Route::get('delivery', 'DeliveryController@index')->name('delivery.index');
    Route::get('delivery/product_delivery/{id}', 'DeliveryController@productDeliveryData');
    Route::get('delivery/create/{id}', 'DeliveryController@create');
    Route::post('delivery/store', 'DeliveryController@store')->name('delivery.store');
    Route::post('delivery/sendmail', 'DeliveryController@sendMail')->name('delivery.sendMail');
    Route::get('delivery/{id}/edit', 'DeliveryController@edit');
    Route::post('delivery/update', 'DeliveryController@update')->name('delivery.update');
    Route::post('delivery/deletebyselection', 'DeliveryController@deleteBySelection');
    Route::post('delivery/delete/{id}', 'DeliveryController@delete')->name('delivery.delete');

    Route::post('quotations/quotation-data', 'QuotationController@quotationData')->name('quotations.data');
    Route::get('quotations/product_quotation/{id}', 'QuotationController@productQuotationData');
    Route::get('quotations/lims_product_search', 'QuotationController@limsProductSearch')->name('product_quotation.search');
    Route::get('quotations/getcustomergroup/{id}', 'QuotationController@getCustomerGroup')->name('quotation.getcustomergroup');
    Route::get('quotations/getproduct/{id}', 'QuotationController@getProduct')->name('quotation.getproduct');
    Route::get('quotations/{id}/create_sale', 'QuotationController@createSale')->name('quotation.create_sale');
    Route::get('quotations/{id}/create_purchase', 'QuotationController@createPurchase')->name('quotation.create_purchase');
    Route::post('quotations/sendmail', 'QuotationController@sendMail')->name('quotation.sendmail');
    Route::post('quotations/deletebyselection', 'QuotationController@deleteBySelection');
    Route::resource('quotations', 'QuotationController');

    Route::post('purchases/purchase-data', 'PurchaseController@purchaseData')->name('purchases.data');
    Route::get('purchases/product_purchase/{id}', 'PurchaseController@productPurchaseData');
    // Route::get('purchases/lims_product_search', 'PurchaseController@limsProductSearch')->name('product_purchase.search');
    Route::get('purchases/lims_product_search', '\App\Http\Controllers\V1\PurchaseController@limsProductSearch')->name('product_purchase.search');
    Route::post('purchases/add_payment', 'PurchaseController@addPayment')->name('purchase.add-payment');
    Route::get('purchases/getpayment/{id}', 'PurchaseController@getPayment')->name('purchase.get-payment');

app/app/Models/Discount.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class Discount extends BaseModel
{
    use HasFactory;

    /** Startr of Caching Settings */
    
    public $cacheTags = ['discounts'];
    public $cachePrefix = 'discounts_';
    /** End of Caching Settings */

    protected $fillable = ['name', 'applicable_for', 'product_list', 'valid_from', 'valid_till', 'type', 'value', 'minimum_qty', 'maximum_qty', 'days', 'is_active'];

    public function discountPlans()
    {
        return $this->belongsToMany(DiscountPlan::class, 'discount_plan_discounts');
    }
}

app/app/Http/Controllers/DiscountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Discount;
use App\Models\DiscountPlan;
use App\Models\Product;
use App\Models\DiscountPlanDiscount;
use Spatie\Permission\Models\Role;
use Auth;

class DiscountController extends Controller
{
    public function index()
    {
        if(auth()->check() && auth()->user()->hasPermissionTo('discount_plan')) {
            $lims_discount_all = Discount::with('discountPlans')->orderBy('id', 'desc')->get();
            return view('backend.discount.index', compact('lims_discount_all'));
        }
        else
            return redirect()->back()->with('not_permitted', 'Sorry! You are not allowed to access this module');
    }

    public function create()
    {
        $lims_discount_plan_list = DiscountPlan::where('is_active', true)->get();
        return view('backend.discount.create', compact('lims_discount_plan_list'));
    }

    public function productSearch($code)
    {
        $lims_product_data = Product::where([
            ['code', $code],
            ['is_active', true]
        ])->select('id', 'name', 'code')->first();

        $product[] = $lims_product_data->id;
        $product[] = $lims_product_data->name;
        $product[] = $lims_product_data->code;
        return $product;
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $data['valid_from'] = date('Y-m-d', strtotime($data['valid_from']));
        $data['valid_till'] = date('Y-m-d', strtotime($data['valid_till']));
        if(isset($data['product_list'])) {
            $data['product_list'] = implode(",", $data['product_list']);
        }
        $data['days'] = implode(",", $data['days']);
        $lims_discount_data = Discount::create($data);
        foreach ($data['discount_plan_id'] as $key => $discount_plan_id) {
            DiscountPlanDiscount::create([
                'discount_id' => $lims_discount_data->id,
                'discount_plan_id' => $discount_plan_id
            ]);
        }
        return redirect()->route('discounts.index')->with('message', 'Discount created successfully');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $lims_discount_data = Discount::find($id);
        $discount_plan_ids = DiscountPlanDiscount::where('discount_id', $id)->pluck('discount_plan_id')->toArray();
        $lims_discount_plan_list = DiscountPlan::where('is_active', true)->get();
        return view('backend.discount.edit', compact('lims_discount_data', 'discount_plan_ids', 'lims_discount_plan_list'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $lims_discount_data = Discount::find($id);
        $data['valid_from'] = date('Y-m-d', strtotime(str_replace("/", "-", $data['valid_from'])));
        $data['valid_till'] = date('Y-m-d', strtotime(str_replace("/", "-", $data['valid_till'])));
        if(!isset($data['is_active']))
            $data['is_active'] = 0;
        if($data['applicable_for'] == 'All')
            $data['product_list'] = '';
        elseif(isset($data['product_list']))
            $data['product_list'] = implode(",", $data['product_list']);
        $data['days'] = implode(",", $data['days']);
        $pre_discount_plan_ids = DiscountPlanDiscount::where('discount_id', $id)->pluck('discount_plan_id')->toArray();
        //deleting previous discount plan id if not exist
        foreach ($pre_discount_plan_ids as $key => $discount_plan_id) {
            if(!in_array($discount_plan_id, $data['discount_plan_id'])) {
                DiscountPlanDiscount::where([
                    ['discount_plan_id', $discount_plan_id],
                    ['discount_id', $id]
                ])->first()->delete();
            }
        }
        //inserting new discount plan id
        foreach ($data['discount_plan_id'] as $key => $discount_plan_id) {
            if(!in_array($discount_plan_id, $pre_discount_plan_ids)) {
                DiscountPlanDiscount::create(['discount_plan_id' => $id, 'discount_id' => $id]);
            }
        }
        $lims_discount_data->update($data);
        return redirect()->route('discounts.index')->with('message', 'Discount updated successfully');
    }

    public function destroy($id)
    {
        //
    }
}

app/resources/views/backend/discount/index.blade.php
@extends('backend.layout.main') @section('content')
@if(session()->has('message'))
  <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{!! session()->get('message') !!}</div>
@endif
@if(session()->has('not_permitted'))
  <div class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('not_permitted') }}</div>
@endif
<section>
    <div class="container-fluid">
        <a href="{{route('discounts.create')}}" class="btn btn-info"><i class="dripicons-plus"></i> {{trans('file.Create Discount')}}</a>&nbsp;
    </div>
    <div class="table-responsive">
        <table id="discount-table" class="table">
            <thead>
                <tr>
                    <th class="not-exported"></th>
                    <th>{{trans('file.name')}}</th>
                    <th>{{trans('file.Value')}}</th>
                    <th>{{trans('file.Discount Plan')}}</th>
                    <th>{{trans('file.Validity')}}</th>
                    <th>{{trans('file.Days')}}</th>
                    <th>{{trans('file.Products')}}</th>
                    <th>{{trans('file.Status')}}</th>
                    <th class="not-exported">{{trans('file.action')}}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($lims_discount_all as $key=> $discount)
                <tr data-id="{{$discount->id}}">
                    <td>{{$key}}</td>
                    <td>{{ $discount->name }}</td>
                    <td>{{ $discount->value.' (' . $discount->type . ')' }}</td>
                    <td>
                        @foreach($discount->discountPlans as $index => $discount_plan)
                            @if($index)
                                {{', '.$discount_plan->name}}
                            @else
                                {{$discount_plan->name}}
                            @endif
                        @endforeach
                    </td>
                    <td>{{date($general_setting->date_format, strtotime($discount->valid_from)).'-'.date($general_setting->date_format, strtotime($discount->valid_till))}}</td>
                    <td>{{ $discount->days }}</td>
                    <td>
                        @if($discount->product_list)
                            <?php $products = \App\Models\Product::select('name', 'code')->whereIn('id', explode(",", $discount->product_list))->get(); ?>
                            @foreach($products as $index => $product)
                                @if($index)
                                    {{', '.$product->name.'['.$product->code.']'}}
                                @else
                                    {{$product->name.'['.$product->code.']'}}
                                @endif
                            @endforeach
                        @else
                            {{trans('file.All Products')}}
                        @endif
                    </td>
                    @if($discount->is_active)
                        <td>{{ trans('file.Active')}}</td>
                    @else
                        <td>{{ trans('file.Inactive')}}</td>
                    @endif
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{trans('file.action')}}
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu edit-options dropdown-menu-right dropdown-default" user="menu">
                                <li>
                                    <a href="{{ route('discounts.edit', $discount->id) }}" class="btn btn-link"><i class="dripicons-document-edit"></i> {{trans('file.edit')}}</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</section>

{{ Form::close() }}


@endsection

@push('scripts')
<script type="text/javascript">

    $("ul#setting").siblings('a').attr('aria-expanded','true');
    $("ul#setting").addClass("show");
    $("ul#setting #discount-list-menu").addClass("active");

    var biller_id = [];
    var user_verified = <?php echo json_encode(env('USER_VERIFIED')) ?>;

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    function confirmDelete() {
        if (confirm("Are you sure want to delete?")) {
            return true;
        }
        return false;
    }
    var table = $('#discount-table').DataTable( {
        "order": [],
        'language': {
            'lengthMenu': '_MENU_ {{trans("file.records per page")}}',
             "info":      '<small>{{trans("file.Showing")}} _START_ - _END_ (_TOTAL_)</small>',
            "search":  '{{trans("file.Search")}}',
            'paginate': {
                    'previous': '<i class="dripicons-chevron-left"></i>',
                    'next': '<i class="dripicons-chevron-right"></i>'
            }
        },
        'columnDefs': [
            {
                "orderable": false,
                'targets': [0, 2, 3, 4]
            },
            {
                'render': function(data, type, row, meta){
                    if(type === 'display'){
                        data = '<div class="checkbox"><input type="checkbox" class="dt-checkboxes"><label></label></div>';
                    }

                   return data;
                },
                'checkboxes': {
                   'selectRow': true,
                   'selectAllRender': '<div class="checkbox"><input type="checkbox" class="dt-checkboxes"><label></label></div>'
                },
                'targets': [0]
            }
        ],
        'select': { style: 'multi',  selector: 'td:first-child'},
        'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, "All"]],
        dom: '<"row"lfB>rtip',
        buttons: [
            {
                extend: 'pdf',
                text: '<i title="export to pdf" class="fa fa-file-pdf-o"></i>',
                exportOptions: {
                    columns: ':visible:Not(.not-exported)',
                    rows: ':visible',
                    stripHtml: false
                }
            },
            {
                extend: 'excel',
                text: '<i title="export to excel" class="dripicons-document-new"></i>',
                exportOptions: {
                    columns: ':visible:Not(.not-exported)',
                    rows: ':visible'
                },
            },
            {
                extend: 'csv',
                text: '<i title="export to csv" class="fa fa-file-text-o"></i>',
                exportOptions: {
                    columns: ':visible:Not(.not-exported)',
                    rows: ':visible',
                },
            },
            {
                extend: 'print',
                text: '<i title="print" class="fa fa-print"></i>',
                exportOptions: {
                    columns: ':visible:Not(.not-exported)',
                    rows: ':visible',
                    stripHtml: false
                }
            },
            {
                extend: 'colvis',
                text: '<i title="column visibility" class="fa fa-eye"></i>',
                columns: ':gt(0)'
            },
        ],
    } );

</script>
@endpush