app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('migrate', 'App\Http\Controllers\LandingPageController@migrateDB');

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('clear', function () {
    Artisan::call('optimize:clear');
    dd('success');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'HomeController@dashboard');
});

Route::group(['middleware' => ['common', 'auth', 'active']], function () {
    Route::get('search/products', '\App\Http\Controllers\V1\SearchController@product')->name('search.products');


    Route::get('/', 'HomeController@index');
    Route::get('switch-theme/{theme}', 'HomeController@switchTheme')->name('switchTheme');
    Route::get('/dashboard-filter/{start_date}/{end_date}', 'HomeController@dashboardFilter');
    Route::get('check-batch-availability/{product_id}/{batch_no}/{warehouse_id}', 'ProductController@checkBatchAvailability');

    Route::get('language_switch/{locale}', 'LanguageController@switchLanguage');

    Route::get('role/permission/{id}', 'RoleController@permission')->name('role.permission');
    Route::post('role/set_permission', 'RoleController@setPermission')->name('role.setPermission');
    Route::resource('role', 'RoleController');

    Route::post('importunit', 'UnitController@importUnit')->name('unit.import');
    Route::post('unit/deletebyselection', 'UnitController@deleteBySelection');
    Route::get('unit/lims_unit_search', 'UnitController@limsUnitSearch')->name('unit.search');
    Route::resource('unit', 'UnitController');

    Route::post('category/import', 'CategoryController@import')->name('category.import');
    Route::post('category/deletebyselection', 'CategoryController@deleteBySelection');
    Route::post('category/category-data', 'CategoryController@categoryData');
    Route::resource('category', 'CategoryController');

    Route::post('importbrand', 'BrandController@importBrand')->name('brand.import');
    Route::post('brand/deletebyselection', 'BrandController@deleteBySelection');
    Route::get('brand/lims_brand_search', 'BrandController@limsBrandSearch')->name('brand.search');
    Route::resource('brand', 'BrandController');

    Route::post('importsupplier', 'SupplierController@importSupplier')->name('supplier.import');
    Route::post('supplier/deletebyselection', 'SupplierController@deleteBySelection');
    Route::post('suppliers/clear-due', 'SupplierController@clearDue')->name('supplier.clearDue');
    Route::resource('supplier', 'SupplierController');

    Route::post('importwarehouse', 'WarehouseController@importWarehouse')->name('warehouse.import');
    Route::post('warehouse/deletebyselection', 'WarehouseController@deleteBySelection');
    Route::get('warehouse/lims_warehouse_search', 'WarehouseController@limsWarehouseSearch')->name('warehouse.search');

    Route::prefix('warehouse')
        ->name('warehouse.')
        ->group(function () {
            Route::resource('bins', 'WarehouseBinController');
        });

    Route::resource('warehouse', 'WarehouseController');



    Route::post('importtax', 'TaxController@importTax')->name('tax.import');
    Route::post('tax/deletebyselection', 'TaxController@deleteBySelection');
    Route::get('tax/lims_tax_search', 'TaxController@limsTaxSearch')->name('tax.search');
    Route::resource('tax', 'TaxController');

    //Route::get('products/getbarcode', 'ProductController@getBarcode');
    Route::post('products/product-data', '\App\Http\Controllers\V1\ProductController@productData');
    Route::get('products/gencode', 'ProductController@generateCode');
    // Route::get('products/search', 'ProductController@search');
    Route::get('products/search', '\App\Http\Controllers\V1\API\ProductController@search');
    Route::get('products/saleunit/{id}', 'ProductController@saleUnit');
    Route::get('products/getdata/{id}/{variant_id}', 'ProductController@getData');
    Route::get('products/product_warehouse/{id}', '\App\Http\Controllers\V1\ProductController@productWarehouseData');
    Route::post('importproduct', 'ProductController@importProduct')->name('product.import');
    Route::post('exportproduct', 'ProductController@exportProduct')->name('product.export');
    Route::get('products/print_barcode', 'ProductController@printBarcode')->name('product.printBarcode');
    Route::get('products/lims_product_search', 'ProductController@limsProductSearch')->name('product.search');
    Route::post('products/deletebyselection', 'ProductController@deleteBySelection');
    Route::post('products/update', '\App\Http\Controllers\V1\ProductController@updateProduct');
    Route::get('products/variant-data/{id}', 'ProductController@variantData');
    Route::get('products/history', '\App\Http\Controllers\V1\ProductController@history')->name('products.history');
    Route::post('products/sale-history-data', 'ProductController@saleHistoryData');
    Route::post('products/purchase-history-data', 'ProductController@purchaseHistoryData');
    Route::post('products/sale-return-history-data', 'ProductController@saleReturnHistoryData');
    Route::post('products/stock-adjustment-history-data', '\App\Http\Controllers\V1\ProductController@stockAdjustmentHistoryData');
    Route::post('products/stock-transfer-history-data', '\App\Http\Controllers\V1\ProductController@stockTransferHistoryData');

    Route::post('products/purchase-return-history-data', 'ProductController@purchaseReturnHistoryData');
    Route::resource('products', '\App\Http\Controllers\V1\ProductController');
    Route::post('products', '\App\Http\Controllers\V1\ProductController@store_v2')->name('products.store_v2');


    Route::post('importcustomer_group', 'CustomerGroupController@importCustomerGroup')->name('customer_group.import');
    Route::post('customer_group/deletebyselection', 'CustomerGroupController@deleteBySelection');
    Route::get('customer_group/lims_customer_group_search', 'CustomerGroupController@limsCustomerGroupSearch')->name('customer_group.search');
    Route::resource('customer_group', 'CustomerGroupController');

    Route::resource('discount-plans', 'DiscountPlanController');
    Route::resource('discounts', 'DiscountController');
    Route::get('discounts/product-search/{code}', 'DiscountController@productSearch');

    Route::post('importcustomer', 'CustomerController@importCustomer')->name('customer.import');
    Route::get('customer/getDeposit/{id}', 'CustomerController@getDeposit');
    Route::post('customer/add_deposit', 'CustomerController@addDeposit')->name('customer.addDeposit');
    Route::post('customer/update_deposit', 'CustomerController@updateDeposit')->name('customer.updateDeposit');
    Route::post('customer/deleteDeposit', 'CustomerController@deleteDeposit')->name('customer.deleteDeposit');
    Route::post('customer/deletebyselection', 'CustomerController@deleteBySelection');
    Route::get('customer/lims_customer_search', 'CustomerController@limsCustomerSearch')->name('customer.search');
    Route::post('customers/clear-due', 'CustomerController@clearDue')->name('customer.clearDue');
    Route::resource('customer', 'CustomerController');

    Route::post('importbiller', 'BillerController@importBiller')->name('biller.import');
    Route::post('biller/deletebyselection', 'BillerController@deleteBySelection');
    Route::get('biller/lims_biller_search', 'BillerController@limsBillerSearch')->name('biller.search');
    Route::resource('biller', 'BillerController');

    Route::post('sales/sale-data', 'SaleController@saleData');
    Route::post('sales/sendmail', 'SaleController@sendMail')->name('sale.sendmail');
    Route::get('sales/sale_by_csv', 'SaleController@saleByCsv');
    Route::get('sales/product_sale/{id}', 'SaleController@productSaleData');
    Route::post('importsale', 'SaleController@importSale')->name('sale.import');
    Route::get('pos', 'SaleController@posSale')->name('sale.pos');
    Route::get('sales/lims_sale_search', 'SaleController@limsSaleSearch')->name('sale.search');
    Route::get('sales/lims_product_search', 'SaleController@limsProductSearch')->name('product_sale.search');
    Route::get('sales/getcustomergroup/{id}', 'SaleController@getCustomerGroup')->name('sale.getcustomergroup');
    Route::get('sales/getproduct/{id}', 'SaleController@getProduct')->name('sale.getproduct');
    Route::get('sales/getproduct/{category_id}/{brand_id}', 'SaleController@getProductByFilter');
    Route::get('sales/getfeatured', 'SaleController@getFeatured');
    Route::get('sales/get_gift_card', 'SaleController@getGiftCard');
    Route::get('sales/paypalSuccess', 'SaleController@paypalSuccess');
    Route::get('sales/paypalPaymentSuccess/{id}', 'SaleController@paypalPaymentSuccess');
    Route::get('sales/gen_invoice/{id}', 'SaleController@genInvoice')->name('sale.invoice');
    Route::post('sales/add_payment', 'SaleController@addPayment')->name('sale.add-payment');
    Route::get('sales/getpayment/{id}', 'SaleController@getPayment')->name('sale.get-payment');
    Route::post('sales/updatepayment', 'SaleController@updatePayment')->name('sale.update-payment');
    Route::post('sales/deletepayment', 'SaleController@deletePayment')->name('sale.delete-payment');
    Route::get('sales/{id}/create', 'SaleController@createSale');
    Route::post('sales/deletebyselection', 'SaleController@deleteBySelection');
    Route::get('sales/print-last-reciept', 'SaleController@printLastReciept')->name('sales.printLastReciept');
    Route::get('sales/today-sale', 'SaleController@todaySale');

app/app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Services\ProductService;

class ProductController extends AbstractBreadController
{
    public array $resources = [
        'index' => '\App\Http\Resources\Product\BrowseCollection',
        'show' => '\App\Http\Resources\Product\ReadResource',
        'update' => '\App\Http\Resources\Product\ReadResource',
        'store' => '\App\Http\Resources\Product\ReadResource',
        'destroy' => '',
    ];

    public function service(): object
    {
        return app(ProductService::class);
    }
}

app/app/Http/Controllers/V1/API/ProductController.php
<?php
namespace App\Http\Controllers\V1\API;

use App\Http\Controllers\Controller;
use App\Services\ProductService;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function search(Request $request)
    {
        $service = app(ProductService::class);
        $result = $service->search($request->all());

        return $result;
    }
}

app/app/Http/Livewire/Product/Form/Admin/PublishStatus.php
<?php

namespace App\Http\Livewire\Product\Form\Admin;

use App\Models\Product;
use App\Services\ProductService;
use Livewire\Component;
use WireUi\Traits\Actions;

class PublishStatus extends Component
{
    use Actions;

    public $product;

    public int $is_active = 0;

    public function mount($product = null)
    {
        $this->product = $product;

        if (!empty($product)) {
            $this->is_active = $product->is_active;
        }
    }

    public function updatedIsActive($value)
    {
        if (!empty($this->product)) {
            (new ProductService)->setPublishStatus($this->product, $value);
            $this->notification()->success(
                'Success',
                'Publish status successfully set'
            );
        }
        $this->emitUp('propertyUpdate', 'is_active', $value);
    }

    public function render()
    {
        return view('livewire.product.form.admin.publish-status');
    }
}

app/app/Http/Livewire/Product/Form/ExtraFields.php
<?php

namespace App\Http\Livewire\Product\Form;

use Livewire\Component;

class ExtraFields extends Component
{
    public $product;

    public $year;
    
    public $version;

    public function mount()
    {
        // $this->product = $product;
    }

    public function render()
    {
        return view('livewire.product.form.extra-fields');
    }
}

app/app/Http/Livewire/Product/History/Filter.php
<?php

namespace App\Http\Livewire\Product\History;

use App\Repositories\Warehouse\WarehouseRepository;
use Livewire\Component;

class Filter extends Component
{
    public $warehouseId;

    public $startingDate;

    public $endingDate;

    public $product;

    public function mount($product)
    {
        $this->product = $product;
    }

    public function filter()
    {
        $filter = [
            'warehouse_id' => $this->warehouseId,
            'start_at' => $this->startingDate,
            'end_at' => $this->endingDate
        ];

        $this->emit('applyeFilters', $filter);
        $this->emit('printProductPurchases', $filter);
    }

    public function updatedWarehouseId($value)
    {
        $this->filter();
    }

    public function updated()
    {
        $this->filter();
    }

    public function set()
    {
        dd('set');
    }

    public function render()
    {
        $warehouses = (new WarehouseRepository)->getAllActive();
        return view(
            'livewire.product.history.filter',

            compact('warehouses')
        );
    }
}

app/app/Http/Livewire/Product/History/Index.php
<?php

namespace App\Http\Livewire\Product\History;

use App\Models\Product;
use Livewire\Component;

class Index extends Component
{
    public $productId;

    public $product;

    // TEMP
    public $product_data = [];
    
    public $name;

    public function mount($productId)
    {
        $this->productId = $productId;


        $this->product = Product::find($productId);
    }

    public function render()
    {
        return view(
            'livewire.product.history.index'
        );
    }
}

app/app/Http/Livewire/Product/History/Print/PrintPurchaseHistory.php
<?php

namespace App\Http\Livewire\Product\History\Print;

use Livewire\Component;
use App\Services\ProductPurchaseService;

class PrintPurchaseHistory extends Component
{
    public $data = null;
    public int $productId;

    public $listeners = ['printProductPurchases'];

    public function mount($productId)
    {
        $this->productId  = $productId;
        $this->printProductPurchases();
    }

    public function render()
    {
        return view('livewire.product.history.print-purchase-history');
    }

    public function printProductPurchases(array $filters = [])
    {
        $this->data = ProductPurchaseService::filter($filters, $this->productId);
    }
}

app/app/Http/Livewire/Product/History/Print/PrintSaleHistory.php
<?php

namespace App\Http\Livewire\Product\History\Print;

use Livewire\Component;
use App\Services\ProductSaleService;

class PrintSaleHistory extends Component
{
    public $data = null;
    public int $productId;

    public $listeners = ['printProductSales'];

    public function mount($productId)
    {
        $this->productId  = $productId;
        $this->printProductSales();
    }

    public function render()
    {
        return view('livewire.product.history.print-sale-history');
    }

    public function printProductSales(array $filters = [])
    {
        $this->data = ProductSaleService::filter($filters, $this->productId);
    }
}

app/resources/views/backend/product/create.blade.php
@extends('backend.layout.main')

@section('content')

<section class="forms">
    <div class="container-fluid">
        @if(session()->has('create_message'))
        <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('create_message') }}</div>
        @endif
        @if(session()->has('edit_message'))
        <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('edit_message') }}</div>
        @endif
        @if(session()->has('import_message'))
        <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('import_message') }}</div>
        @endif
        @if(session()->has('not_permitted'))
        <div class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('not_permitted') }}</div>
        @endif
        @if(session()->has('message'))
        <div class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('message') }}</div>
        @endif
        
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h4>{{trans('file.add_product')}}</h4>
                    </div>
                </div>

                <livewire:product.form.product :product="$lims_product_data" />

            </div>
        </div>
</section>


@endsection

app/resources/views/backend/product/edit.blade.php
@extends('backend.layout.main')

@section('content')

<section class="forms">
    <div class="container-fluid">
        @if(session()->has('create_message'))
        <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('create_message') }}</div>
        @endif
        @if(session()->has('edit_message'))
        <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('edit_message') }}</div>
        @endif
        @if(session()->has('import_message'))
        <div class="alert alert-success alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('import_message') }}</div>
        @endif
        @if(session()->has('not_permitted'))
        <div class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('not_permitted') }}</div>
        @endif
        @if(session()->has('message'))
        <div class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ session()->get('message') }}</div>
        @endif
        
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h4>{{trans('file.edit_product')}}</h4>
                    </div>
                </div>

                <livewire:product.form.product :product="$lims_product_data" />

            </div>
        </div>
</section>


@endsection

app/resources/views/backend/product/index.blade.php
@extends('backend.layout.main') @section('content')
    @if (session()->has('create_message'))
        <div class="alert alert-success alert-dismissible text-center"><button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
            ><span aria-hidden="true">&times;</span></button>{{ session()->get('create_message') }}</div>
    @endif
    @if (session()->has('edit_message'))
        <div class="alert alert-success alert-dismissible text-center"><button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
            ><span aria-hidden="true">&times;</span></button>{{ session()->get('edit_message') }}</div>
    @endif
    @if (session()->has('import_message'))
        <div class="alert alert-success alert-dismissible text-center"><button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
            ><span aria-hidden="true">&times;</span></button>{{ session()->get('import_message') }}</div>
    @endif
    @if (session()->has('not_permitted'))
        <div class="alert alert-danger alert-dismissible text-center"><button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
            ><span aria-hidden="true">&times;</span></button>{{ session()->get('not_permitted') }}</div>
    @endif
    @if (session()->has('message'))
        <div class="alert alert-danger alert-dismissible text-center"><button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
            ><span aria-hidden="true">&times;</span></button>{{ session()->get('message') }}</div>
    @endif

    <section>
        <div class="container-fluid">
            @if (in_array('products-add', $all_permission))
                <a
                    href="{{ route('products.create') }}"
                    class="btn btn-info"
                ><i class="dripicons-plus"></i> {{ __('file.add_product') }}</a>
                <a
                    href="#"
                    data-toggle="modal"
                    data-target="#importProduct"
                    class="btn btn-primary"
                ><i class="dripicons-copy"></i> {{ __('file.import_product') }}</a>
            @endif
        </div>
        <div class="table-responsiv">
            <div
                id="product-data-table_wrapper"
                class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer"
            >
                <div class="card">
                    <div class="card-body">
                        <livewire:product.browse />
                    </div>
                </div>
                {{-- <livewire:product.browse /> --}}
            </div>
        </div>
    </section>


    @push('styles')
        <style>
            #product-data-table_wrapper .table-row:first-child div:first-child div {
                display: none;
            }

            #product-data-table_wrapper .table-row:first-child div button {
                padding: 2px !important;
                /* height: auto; */
                text-align: center;
            }

            #product-data-table_wrapper .table-row:nth-child(2) div:first-child {
                padding: 5px !important;
            }

            #product-data-table_wrapper .datatable-footer {}
        </style>
    @endpush
@endsection

app/resources/views/backend/product/show.blade.php
@extends('backend.layout.main')


@section('content')
    <section>
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h2>{{ trans('Product Details') }}</h2>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td class="label">{{ trans('file.Product Name') }}</td>
                                <td class="value">{{ $product->name }}</td>
                            </tr>
                            <tr>
                                <td class="label">{{ trans('file.Product Code') }}</td>
                                <td class="value">{{ $product->code }}</td>
                            </tr>
                            <tr>
                                <td class="label">{{ trans('file.Quantity') }}</td>
                                <td class="value">
                                    {{ $product->warehouses->sum(fn($warehouse) => $warehouse->pivot->qty, 0) }}</td>
                            </tr>

                            <tr>
                                <td class="label">{{ trans('file.Product Unit') }}</td>
                                <td class="value">{{ $product->unit->unit_code }}</td>
                            </tr>

                            <tr>
                                <td class="label">{{ trans('file.Product Price') }}</td>
                                <td class="value">{{ $product->price }}</td>
                            </tr>

                            <tr>
                                <td class="label">{{ trans('file.Product Details') }}</td>
                                <td class="value">{!! $product->product_details !!}</td>
                            </tr>

                            <tr>
                                <td class="label">{{ trans('file.Alert Quantity') }}</td>
                                <td class="value">{{ $product->alert_quantity }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>




            <!-- <button id="print-btn" type="button" class="btn btn-default btn-sm ml-3"><i class="dripicons-print"></i> {{ trans('file.Print') }}</button>
                    <button type="button" id="close-btn" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true"><i class="dripicons-cross"></i></span></button> -->


            <div class="card">
                <div class="card-header">
                    <h2>{{ trans('file.Warehouse Quantity') }} (Stocks on-hand)</h2>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-hover product-warehouse-list">
                        <thead>
                            <tr>
                                <th>Warehouse</th>
                                {{-- <th>Bin Location</th> --}}
                                {{-- <th>Batch No</th> --}}
                                {{-- <th>Expired Date</th> --}}
                                <th>Quantity</th>
                                {{-- <th>IMEI or Serial Numbers</th> --}}
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($stocks as $warehouse)
                                <tr>
                                    <td>{{ $warehouse->name }}</td>
                                    {{-- <td>
                                        {{ $warehouse->bin_name ?? 'N/A' }}
                                    </td> --}}
                                    {{-- <td>Batch No</td> --}}
                                    {{-- <td>Expired Date</td> --}}
                                    <td>{{ $warehouse->qty }} {{ $product->unit->unit_code }}</td>
                                    {{-- <td>IMEI or Serial Numbers</td> --}}
                                </tr>
                            @endforeach


                            @if (empty($product->warehouses->count()))
                                <tr>
                                    <td
                                        colspan="2"
                                        class="text-center"
                                    >
                                        <em>No entries yet</em>
                                    </td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('styles')
    <style>
        .card-body table .label {
            font-weight: bold;
            width: 20%;
        }

        .card-body table .value {}
    </style>
@endpush